export const mockData = {
  config: {
    externalFilter: [
      {
        title: "Status",
        field: "status",
        type: "dropdown",
        options: [
          {
            label: "Select Status",
            value: "",
          },
          {
            label: "Pass",
            value: "pass",
          },
          {
            label: "Fail",
            value: "fail",
          }
        ]
      },
      {
        title: "Group",
        field: "group",
        type: "dropdown",
        options: [
          {
            label: "Select Group",
            value: "",
          },
          {
            label: "Group A",
            value: "A"
          },
          {
            label: "Group B",
            value: "B"
          },
          {
            label: "Group C",
            value: "C"
          },
          {
            label: "Group D",
            value: "D"
          },
        ]
      }
    ],
    columnDefs: [
      {
        visible: true,
        headerName: "First Name",
        headerClass: "firstName",
        field: "firstName",
        columnTypeParams: [],
        filterType: "text",
        width: 120,
        textStyle: {
          textAlign: "left",
        },
      },
      {
        visible: true,
        headerName: "Middle Name",
        headerClass: "middleName",
        field: "middleName",
        columnTypeParams: [],
        filterType: "text",
        width: 120,
        textStyle: {
          textAlign: "left",
        },
      },
      {
        visible: true,
        headerName: "Last Name",
        headerClass: "lastName",
        field: "lastName",
        columnTypeParams: [],
        filterType: "text",
        width: 120,
        textStyle: {
          textAlign: "left",
        },
      },
      {
        visible: true,
        headerName: "Age",
        headerClass: "age",
        field: "age",
        columnTypeParams: ['numericColumn'],
        filterType: "number",
        width: 90,
        textStyle: {
          textAlign: "center",
        },
      },
      {
        visible: true,
        headerName: "Birthday",
        headerClass: "birthday",
        field: "birthday",
        columnTypeParams: "",
        filterType: "date",
        textStyle: {
          textAlign: "center",
        },
      },
      {
        visible: true,
        headerName: "Gender",
        headerClass: "gender",
        field: "gender",
        columnTypeParams: "",
        filterType: "text",
        textStyle: {
          textAlign: "left",
        },
      },
      {
        visible: true,
        headerName: "Address",
        headerClass: "address",
        field: "address",
        columnTypeParams: "",
        filterType: "text",
        textStyle: {
          textAlign: "left",
        },
      },
      {
        visible: true,
        headerName: "Status",
        headerClass: "pass",
        field: "pass",
        columnTypeParams: "",
        filterType: "",
        textStyle: {
          textAlign: "center",
        },
      },
      {
        visible: true,
        headerName: "Grade",
        headerClass: "grade",
        field: "grade",
        columnTypeParams: ['numericColumn'],
        filterType: "number",
        textStyle: {
          textAlign: "center",
        },
      },
      {
        visible: true,
        headerName: "Group",
        headerClass: "group",
        field: "group",
        width: 90,
        columnTypeParams: "",
        filterType: "",
        textStyle: {
          textAlign: "center",
        },
      },
    ]
  },
  data: [
    {
      firstName: "Olive",
      middleName: "Teak",
      lastName: "Yew",
      age: 38,
      birthday: "29/08/1982",
      gender: "Female",
      address: "Arch Hill",
      pass: true,
      grade: 89.89,
      group: "A",
    },
    {
      firstName: "Aida",
      middleName: "Anthemum",
      lastName: "Bugg",
      age: 30,
      birthday: "10/11/1990",
      gender: "Female",
      address: "Auckland CBD",
      pass: true,
      grade: 91.33,
      group: "B",
    },
    {
      firstName: "Ray",
      middleName: "Gon",
      lastName: "Sin",
      age: 36,
      birthday: "06/01/1985",
      gender: "Male",
      address: "Avondale",
      pass: false,
      grade: 74.71,
      group: "C",
    },
    {
      firstName: "Augusto",
      middleName: "Mori",
      lastName: "Wind",
      age: 32,
      birthday: "12/12/1988",
      gender: "Male",
      address: "Blockhouse Bay",
      pass: true,
      grade: 85.28,
      group: "D",
    },
    {
      firstName: "Lee",
      middleName: "Annd",
      lastName: "Sun",
      age: 34,
      birthday: "30/01/1987",
      gender: "Male",
      address: "Balmoral",
      pass: true,
      grade: 89.76,
      group: "A",
    },
    {
      firstName: "Isabelle",
      middleName: "Daza",
      lastName: "Ringing",
      age: 23,
      birthday: "19/04/1998",
      gender: "Female",
      address: "Blackpool",
      pass: false,
      grade: 73.45,
      group: "B",
    },
    {
      firstName: "Constance",
      middleName: "Tinople",
      lastName: "Noring",
      age: 31,
      birthday: "12/08/1989",
      gender: "Male",
      address: "Eden Terrace",
      pass: false,
      grade: 72.99,
      group: "C",
    },
    {
      firstName: "Liz",
      middleName: "Vin",
      lastName: "Erd",
      age: 35,
      birthday: "02/04/1986",
      gender: "Male",
      address: "Eden Valley",
      pass: false,
      grade: 69.11,
      group: "D",
    },
    {
      firstName: "Eileen",
      middleName: "White",
      lastName: "Sideways",
      age: 22,
      birthday: "05/12/1999",
      gender: "Female",
      address: "Ellerslie",
      pass: true,
      grade: 81.87,
      group: "A",
    },
    {
      firstName: "Allie",
      middleName: "Peak",
      lastName: "Grater",
      age: 26,
      birthday: "10/10/1994",
      gender: "Male",
      address: "Epsom",
      pass: false,
      grade: 71.54,
      group: "B",
    },
    {
      firstName: "Minnie",
      middleName: "Van",
      lastName: "Ryder",
      age: 24,
      birthday: "28/06/1997",
      gender: "Female",
      address: "Freemans Bay",
      pass: true,
      grade: 80.12,
      group: "C",
    },
    {
      firstName: "Lois",
      middleName: "Di",
      lastName: "Nominator",
      age: 42,
      birthday: "17/03/1979",
      gender: "Male",
      address: "Glendowie",
      pass: true,
      grade: 78.56,
      group: "D",
    },
    {
      firstName: "Rita",
      middleName: "Paige",
      lastName: "Book",
      age: 37,
      birthday: "29/09/1983",
      gender: "Female",
      address: "Glen Innes",
      pass: false,
      grade: 73.88,
      group: "A",
    },
    {
      firstName: "Peg",
      middleName: "Alice",
      lastName: "Legge",
      age: 27,
      birthday: "11/07/1994",
      gender: "Female",
      address: "Grafton",
      pass: false,
      grade: 71.90,
      group: "B",
    },
    {
      firstName: "Shein",
      middleName: "Dine",
      lastName: "Wayne",
      age: 42,
      birthday: "17/07/1979",
      gender: "Male",
      address: "Greenlane",
      pass: true,
      grade: 87.43,
      group: "C",
    },
    {
      firstName: "Ray",
      middleName: "Neal",
      lastName: "Sun",
      age: 23,
      birthday: "25/11/1997",
      gender: "Male",
      address: "Greenwoods Corner",
      pass: false,
      grade: 69.66,
      group: "D",
    },
    {
      firstName: "Teri",
      middleName: "Owen",
      lastName: "Dactly",
      age: 33,
      birthday: "22/01/1988",
      gender: "Male",
      address: "Grey Lynn",
      pass: false,
      grade: 73.78,
      group: "A",
    },
    {
      firstName: "Maureen",
      middleName: "Kane",
      lastName: "Biologist",
      age: 20,
      birthday: "13/10/2000",
      gender: "Female",
      address: "Herne Bay",
      pass: true,
      grade: 93.68,
      group: "B",
    },
    {
      firstName: "Rhoda",
      middleName: "Mann",
      lastName: "Report",
      age: 35,
      birthday: "09/05/1986",
      gender: "Female",
      address: "Hillsborough",
      pass: true,
      grade: 91.88,
      group: "C",
    },
    {
      firstName: "Leift",
      middleName: "Dean",
      lastName: "Thurn",
      age: 37,
      birthday: "04/12/1983",
      gender: "Male",
      address: "Kingsland",
      pass: true,
      grade: 92.67,
      group: "D",
    },
  ]
};